export const RouteNames = {
  WELCOME: 'home',
  INVESTOR_SIGNUP: 'investor-register',
  ISSUER_SIGNUP: 'issuer-register',
  COUNTRY: 'select-country',
  COMPANY_INFORMATION: 'company-information',
  MOBILE: 'register-mobile',
  VERIFY_MOBILE: 'verify-mobile',
  REGISTER_EMAIL: 'register-email',
  VERIFY_EMAIL: 'verify-email',
  CREATE_PASSWORD: 'create-password',
  LOGIN: 'login',
  NOT_FOUND: '*',
  ABOUT_OUR_SERVICES: 'about-our-services',
  HELP: 'help',
  BUSINESS_CATEGORY: 'business-category',
  SOURCE_OF_FUNDING: 'source-of-funding',
  BUSINESS_DESCRIPTION: 'business-description',
  BUSINESS_REGULATION: 'business-regulation',
  BUSINESS_REVENUE: 'business-revenue',
  BUSINESS_TURNOVER: 'business-turnover',
  PERSONAL_INFORMATION: 'personal-information',
  ADDRESS: 'address',
  QUESTIONS_LIST: 'questions-list'
} as const;
